platform: Microsoft Sentinel
source: windows_security


log_source:
  table: [SecurityEvent, WindowsEvent]

default_log_source:
  table: SecurityEvent

field_mapping:
  EventID: EventID
  ParentImage: ParentProcessName
  AccessMask: AccessMask
  AccountName: AccountName
  AllowedToDelegateTo: AllowedToDelegateTo
  AttributeLDAPDisplayName:
  AuditPolicyChanges: AuditPolicyChanges
  AuthenticationPackageName: AuthenticationPackageName
  CallingProcessName: CallingProcessName
  Channel: Channel
  ComputerName: Computer
  EventType: EventType
  FailureReason: FailureReason
  FileName: FilePath
  GrantedAccess:
  Hashes: FileHash
  HiveName: HiveName
  IpAddress: IpAddress
  IpPort: IpPort
  KeyLength: KeyLength
  LogonProcessName: LogonProcessName
  LogonType: LogonType
  LinkName: LinkName
  MemberName: MemberName
  MemberSid: MemberSid
  NewProcessName: NewProcessName
  ObjectClass: ObjectClass
  ObjectName: ObjectName
  ObjectType: ObjectType
  ObjectValueName: ObjectValueName
  Path: Path
  CommandLine: CommandLine
  OldUacValue: OldUacValue
  CertIssuerName: CertIssuerName
  SubStatus: SubStatus
  DisplayName: DisplayName
  TaskContent: TaskContent
  ServiceSid: ServiceSid
  CertThumbprint: CertThumbprint
  ClassName: duplicate
  NotificationPackageName: ClassName
  NewSd: NewSd
  TestSigning: TestSigning
  TargetInfo: TargetInfo
  ClientProcessId: TargetInfo
  ParentProcessId: ParentProcessId
  AccessList: AccessList
  GroupMembership: GroupMembership
  FilterName: FilterName
  ChangeType: ChangeType
  LayerName: LayerName
  ServiceAccount: ServiceAccount
  AttributeValue: ServiceAccount
  SessionName: SessionName
  TaskName: TaskName
  ObjectDN: SessionName
  TemplateContent: TemplateContent
  NewTemplateContent: NewTemplateContent
  SourcePort: TemplateContent
  PasswordLastSet: PasswordLastSet
  PrivilegeList: PrivilegeList
  DeviceDescription: PasswordLastSet
  TargetServerName: PrivilegeList
  NewTargetUserName: DeviceDescription
  OperationType: TargetServerName
  DestPort: DestPort
  ServiceStartType: OperationType
  OldTargetUserName: OldTargetUserName
  UserPrincipalName: ServiceStartType
  Accesses: Accesses
  DnsHostName: UserPrincipalName
  DisableIntegrityChecks: AccessList
  AuditSourceName: AuditSourceName
  Workstation: Workstation
  DestAddress: DestAddress
  PreAuthType: Workstation
  SecurityPackageName: SecurityPackageName
  SubjectLogonId: SubjectLogonId
  NewUacValue: NewUacValue
  EnabledPrivilegeList: SubjectLogonId
  RelativeTargetName: NewUacValue
  CertSerialNumber: CertSerialNumber
  SidHistory: RelativeTargetName
  TargetLogonId: TargetLogonId
  KernelDebug: SidHistory
  CallerProcessName: TargetLogonId
  ProcessName: ProcessName
  Properties: CallerProcessName
  UserAccountControl: ProcessName
  RegistryValue: Properties
  SecurityID: UserAccountControl
  ServiceFileName: ServiceFileName
  SecurityDescriptor: SecurityID
  ServiceName: ServiceFileName
  ShareName: SecurityDescriptor
  NewValue: ServiceName
  Source: ShareName
  Status: NewValue
  SubjectDomainName: SubjectDomainName
  SubjectUserName: Status
  SubjectUserSid: SubjectDomainName
  SourceAddr: SubjectUserName
  SourceAddress: SubjectUserSid
  TargetName: TargetName
  ServicePrincipalNames: ServicePrincipalNames
  TargetDomainName: TargetName
  TargetSid: TargetSid
  TargetUserName: TargetDomainName
  ObjectServer: TargetSid
  TargetUserSid: TargetUserName
  TicketEncryptionType: ObjectServer
  TicketOptions: TargetUserSid
  WorkstationName: WorkstationName
  TransmittedServices: TransmittedServices
  AuthenticationAlgorithm: WorkstationName
  LayerRTID: TransmittedServices
  BSSID: BSSID
  BSSType: BSSType
  CipherAlgorithm: CipherAlgorithm
  ConnectionId: ConnectionId
  ConnectionMode: ConnectionMode
  InterfaceDescription: InterfaceDescription
  InterfaceGuid: InterfaceGuid
  OnexEnabled: OnexEnabled
  PHYType: PHYType
  ProfileName: ProfileName
  SSID: SSID
  Domain: Domain
  ServiceType: ServiceType
  SourceName: SourceName
  StartType: ServiceType
  UserID: UserID
  ParentProcessName: ParentProcessName
  Service: Service
