platform: Qradar
source: windows_security


log_source:
  devicetype: [12]

default_log_source:
  devicetype: 12

field_mapping:
  EventID: Event ID
  ParentImage: Parent Process Path
  AccessMask: AccessMask
  AccountName: Account Name
  AllowedToDelegateTo: AllowedToDelegateTo
  AttributeLDAPDisplayName: AttributeLDAPDisplayName
  AuditPolicyChanges: AuditPolicyChanges
  AuthenticationPackageName: AuthenticationPackageName
  CallingProcessName: CallingProcessName
  Channel: Channel
  ComputerName: Machine Identifier
  EventType: EventType
  FailureReason: FailureReason
  FileName: Filename
  GrantedAccess: GrantedAccess
  Hashes: File Hash
  HiveName: HiveName
  IpAddress: IpAddress
  IpPort: IpPort
  KeyLength: KeyLength
  LogonProcessName: LogonProcessName
  LogonType: Logon Type
  LinkName: LinkName
  MemberName: MemberName
  MemberSid: MemberSid
  NewProcessName: Process Name
  ObjectClass: ObjectClass
  ObjectName: Object Name
  ObjectType: Object Type
  ObjectValueName: ObjectValueName
  Path: Path
  CommandLine: Command
  OldUacValue: OldUacValue
  SubStatus: SubStatus
  DisplayName: DisplayName
  TaskContent: TaskContent
  ServiceSid: ServiceSid
  CertThumbprint: CertThumbprint
  ClassName: ClassName
  NotificationPackageName: NotificationPackageName
  NewSd: NewSd
  TestSigning: TestSigning
  TargetInfo: TargetInfo
  ClientProcessId: ClientProcessId
  ParentProcessId: ParentProcessId
  AccessList: AccessList
  GroupMembership: GroupMembership
  FilterName: FilterName
  ChangeType: ChangeType
  LayerName: LayerName
  ServiceAccount: ServiceAccount
  AttributeValue: AttributeValue
  SessionName: SessionName
  TaskName: TaskName
  ObjectDN: ObjectDN
  TemplateContent: TemplateContent
  NewTemplateContent: NewTemplateContent
  SourcePort: sourceport
  PasswordLastSet: PasswordLastSet
  PrivilegeList: PrivilegeList
  DeviceDescription: DeviceDescription
  TargetServerName: TargetServerName
  NewTargetUserName: NewTargetUserName
  OperationType: OperationType
  DestPort: destinationport
  ServiceStartType: ServiceStartType
  OldTargetUserName: OldTargetUserName
  UserPrincipalName: UserPrincipalName
  Accesses: Accesses
  DnsHostName: DnsHostName
  DisableIntegrityChecks: DisableIntegrityChecks
  AuditSourceName: AuditSourceName
  Workstation: Machine Identifier
  DestAddress: destinationip
  PreAuthType: PreAuthType
  SecurityPackageName: SecurityPackageName
  SubjectLogonId: SubjectLogonId
  NewUacValue: NewUacValue
  EnabledPrivilegeList: EnabledPrivilegeList
  RelativeTargetName: RelativeTargetName
  CertSerialNumber: RelativeTargetName
  SidHistory: SidHistory
  TargetLogonId: TargetLogonId
  KernelDebug: KernelDebug
  CallerProcessName: CallerProcessName
  ProcessName: Process Name
  Properties: Properties
  UserAccountControl: UserAccountControl
  RegistryValue: Target Object
  SecurityID: SecurityID
  ServiceFileName: Service Filename
  SecurityDescriptor: SecurityDescriptor
  ServiceName: Service Name
  ShareName: Share Name
  NewValue: NewValue
  Source: Source
  Status: Status
  SubjectDomainName: SubjectDomainName
  SubjectUserName: Target Username
  SubjectUserSid: SubjectUserSid
  SourceAddr: sourceip
  SourceAddress: sourceip
  TargetName: Target Username
  ServicePrincipalNames: ServicePrincipalNames
  TargetDomainName: TargetDomainName
  TargetSid: TargetSid
  TargetUserName: Target Username
  ObjectServer: ObjectServer
  TargetUserSid: TargetUserSid
  TicketEncryptionType: TicketEncryptionType
  TicketOptions: TicketOptions
  WorkstationName: Machine Identifier
  TransmittedServices: TransmittedServices
  AuthenticationAlgorithm: AuthenticationAlgorithm
  LayerRTID: LayerRTID
  BSSID: BSSID
  BSSType: BSSType
  CipherAlgorithm: CipherAlgorithm
  ConnectionId: ConnectionId
  ConnectionMode: ConnectionMode
  InterfaceDescription: InterfaceDescription
  InterfaceGuid: InterfaceGuid
  OnexEnabled: OnexEnabled
  PHYType: PHYType
  ProfileName: ProfileName
  SSID: SSID
  Domain: Domain
  ServiceType: ServiceType
  SourceName: SourceName
  StartType: StartType
  UserID: UserID
  ParentProcessName: Parent Process Name
  Service: Service