platform: Hunters
source: windows_security


default_log_source:
  table: table_name

field_mapping:
  EventID: EventID
  ParentImage: ParentImage
  AccessMask: AccessMask
  AccountName: AccountName
  AllowedToDelegateTo: AllowedToDelegateTo
  AttributeLDAPDisplayName: AttributeLDAPDisplayName
  AuditPolicyChanges: AuditPolicyChanges
  AuthenticationPackageName: AuthenticationPackageName
  CallingProcessName: CallingProcessName
  Channel: Channel
  ComputerName: ComputerName
  EventType: EventType
  FailureReason: FailureReason
  FileName: FileName
  GrantedAccess: GrantedAccess
  Hashes: Hashes
  HiveName: HiveName
  IpAddress: IpAddress
  IpPort: IpPort
  KeyLength: KeyLength
  LogonProcessName: LogonProcessName
  LogonType: LogonType
  LinkName: LinkName
  MemberName: MemberName
  MemberSid: MemberSid
  NewProcessName: NewProcessName
  ObjectClass: ObjectClass
  ObjectType: ObjectType
  ObjectValueName: ObjectValueName
  Path: Path
  CommandLine: CommandLine
  OldUacValue: OldUacValue
  CertIssuerName: CertIssuerName
  SubStatus: SubStatus
  DisplayName: DisplayName
  TaskContent: TaskContent
  ServiceSid: ServiceSid
  CertThumbprint: CertThumbprint
  ObjectName: ObjectName
  ClassName: ClassName
  NotificationPackageName: NotificationPackageName
  NewSd: NewSd
  TestSigning: TestSigning
  TargetInfo: TargetInfo
  ParentProcessId: ParentProcessId
  AccessList: AccessList
  GroupMembership: GroupMembership
  FilterName: FilterName
  ChangeType: ChangeType
  LayerName: LayerName
  ServiceAccount: ServiceAccount
  ClientProcessId: ClientProcessId
  AttributeValue: AttributeValue
  SessionName: SessionName
  TaskName: TaskName
  ObjectDN: ObjectDN
  TemplateContent: TemplateContent
  NewTemplateContent: NewTemplateContent
  SourcePort: SourcePort
  PasswordLastSet: PasswordLastSet
  PrivilegeList: PrivilegeList
  DeviceDescription: DeviceDescription
  TargetServerName: TargetServerName
  NewTargetUserName: NewTargetUserName
  OperationType: OperationType
  DestPort: DestPort
  ServiceStartType: ServiceStartType
  OldTargetUserName: OldTargetUserName
  UserPrincipalName: UserPrincipalName
  Accesses: Accesses
  DnsHostName: DnsHostName
  DisableIntegrityChecks: DisableIntegrityChecks
  AuditSourceName: AuditSourceName
  Workstation: Workstation
  DestAddress: DestAddress
  PreAuthType: PreAuthType
  SecurityPackageName: SecurityPackageName
  SubjectLogonId: SubjectLogonId
  NewUacValue: NewUacValue
  EnabledPrivilegeList: EnabledPrivilegeList
  RelativeTargetName: RelativeTargetName
  CertSerialNumber: CertSerialNumber
  SidHistory: SidHistory
  TargetLogonId: TargetLogonId
  KernelDebug: KernelDebug
  CallerProcessName: CallerProcessName
  Properties: Properties
  UserAccountControl: UserAccountControl
  RegistryValue: RegistryValue
  SecurityID: SecurityID
  ServiceFileName: ServiceFileName
  SecurityDescriptor: SecurityDescriptor
  ServiceName: ServiceName
  ShareName: ShareName
  NewValue: NewValue
  Source: Source
  Status: Status
  SubjectDomainName: SubjectDomainName
  SubjectUserName: SubjectUserName
  SubjectUserSid: SubjectUserSid
  SourceAddr: SourceAddr
  SourceAddress: SourceAddress
  TargetName: TargetName
  ServicePrincipalNames: ServicePrincipalNames
  TargetDomainName: TargetDomainName
  TargetSid: TargetSid
  TargetUserName: TargetUserName
  ObjectServer: ObjectServer
  TargetUserSid: TargetUserSid
  TicketEncryptionType: TicketEncryptionType
  TicketOptions: TicketOptions
  WorkstationName: WorkstationName
  TransmittedServices: TransmittedServices
  AuthenticationAlgorithm: AuthenticationAlgorithm
  LayerRTID: LayerRTID
  BSSID: BSSID
  BSSType: BSSType
  CipherAlgorithm: CipherAlgorithm
  ConnectionId: ConnectionId
  ConnectionMode: ConnectionMode
  InterfaceDescription: InterfaceDescription
  InterfaceGuid: InterfaceGuid
  OnexEnabled: OnexEnabled
  PHYType: PHYType
  ProfileName: ProfileName
  SSID: SSID
  Domain: Domain
  ServiceType: ServiceType
  SourceName: SourceName
  StartType: StartType
  UserID: UserID
  ParentProcessName: ParentProcessName
  Service: Service
  ProcessName: ProcessName
