platform: FortiSiem
source: windows_security


log_source:
  eventType:
    - Win-Security-4768-success
    - Win-Security-4768-failure
    - Win-Security-4769-failure
    - Win-Security-4769-success

default_log_source:
  eventType: Win-Security-*
