platform: Palo Alto XSIAM
source: default


default_log_source:
  datamodel: datamodel


field_mapping:
  CommandLine: xdm.target.process.command_line
  Image:
    - xdm.target.process.name
    - xdm.source.process.name
  ProcessName:
    - xdm.target.process.name
    - xdm.source.process.name
  ImageLoaded:
    - xdm.target.process.executable.filename
    - xdm.source.process.executable.filename
  ParentCommandLine: xdm.source.process.command_line
  ParentImage: xdm.source.process.name
  User: xdm.source.user.username
  TargetFilename: xdm.target.file.filename
  TargetImage: xdm.target.process.name
  SourceImage: xdm.source.process.name
  EventID: xdm.event.id
  Protocol: xdm.network.ip_protocol
  src-ip: xdm.source.ipv4
  SourceIp: xdm.source.ipv4
  src-packets: xdm.source.sent_packets
  dst-packets: xdm.target.sent_packets
  src-port: xdm.source.port
  SourcePort: xdm.source.port
  dst-ip: xdm.target.ipv4
  DestinationIp: xdm.target.ipv4
  dst-port: xdm.target.port
  DestinationPort: xdm.target.port
  src-bytes: xdm.source.sent_bytes
  dst-bytes: xdm.target.sent_bytes
  src-hostname: xdm.source.host.hostname
  dst-hostname: xdm.target.host.hostname
  icmp.type: xdm.network.icmp.type
  icmp.code: xdm.network.icmp.code
  c-uri: xdm.network.http.url
  c-uri-query: xdm.network.http.url
  QueryName: xdm.network.dns.dns_question.name
  Application: xdm.network.application_protocol
  SourceHostName: xdm.source.host.hostname
  DestinationHostname: xdm.target.host.hostname
  Hashes:
    - xdm.source.process.executable.sha256
    - xdm.source.process.executable.md5
  IntegrityLevel: xdm.source.process.integrity_level
  SourceHostname: xdm.source.host.hostname
  Signed: xdm.source.process.executable.is_signed
  Signature: xdm.source.process.executable.signer
  SignatureStatus: xdm.source.process.executable.signature_status
  QueryResults: xdm.network.dns.dns_resource_record.value
  QueryStatus: xdm.network.dns.response_code
  ImagePath: xdm.target.process.executable.path
  ProcessID: xdm.target.process.pid
  EventType: xdm.event.original_event_type
  dns-query: xdm.network.dns.dns_question.name
  dns-answer: xdm.network.dns.dns_resource_record.value
  dns-record: xdm.network.dns.dns_question.name
  FileName: xdm.target.file.path
  IpAddress: xdm.source.ipv4
  IpPort: xdm.source.port
  LogonProcessName: xdm.target.process.executable.path
  ProcessId: xdm.target.process.pid
  NewProcessName: xdm.target.process.executable.path
  Path: xdm.target.process.executable.path
  ParentProcessId: xdm.source.process.pid
  GroupMembership: xdm.target.user.groups
  NewTargetUserName: xdm.target.user.username
  OldTargetUserName: xdm.target.user.username
  UserPrincipalName: xdm.source.user.username

  DestAddress: xdm.target.ipv4
  SubjectUserName: xdm.source.user.username
  SubjectUserSid: xdm.source.user.identifier
  SourceAddr: xdm.source.ipv4
  SourceAddress: xdm.source.ipv4
  TargetSid: xdm.target.user.identifier
  TargetUserName: xdm.target.user.username
  ParentProcessName: xdm.source.process.executable.path
  client.user.full_name: xdm.target.user.username
  source.user.full_name: xdm.source.user.username
  client.ip: xdm.source.ipv4
  user_agent.original: xdm.network.http.browser
  userAgent.os: xdm.network.http.browser
  userAgent.browser: xdm.network.http.browser
  eventtype: xdm.event.type
  a0: xdm.target.process.command_line
  a1: xdm.target.process.command_line
  a2: xdm.target.process.command_line
  a3: xdm.target.process.command_line
  exe: xdm.target.process.executable.path
  userAgent: xdm.network.http.browser
  userIdentity.userName: userIdentity.userName
  user.username: xdm.source.user.username
  AccountName: xdm.target.user.username
  processPath: xdm.target.process.executable.path
  QNAME: xdm.network.dns.dns_question.name
  ImageName: xdm.target.process.name
  UserName: xdm.source.user.username
  Address: xdm.source.ipv4
  Process_Name: xdm.target.process.executable.path
  uri: xdm.network.http.url
  query: xdm.network.dns.dns_question.name
  referrer: xdm.network.http.referrer
  user_agent: xdm.network.http.browser
  status_code: xdm.network.http.response_code
  qtype_name: xdm.network.dns.opcode
  http.method: xdm.network.http.method
  method: xdm.network.http.method
  notice.user_agent: xdm.network.http.browser
