platform: Graylog
source: windows_security


field_mapping:
  EventID: winlog.event_id
  ParentImage: winlog.event_data.ParentImage
  AccessMask: winlog.event_data.AccessMask
  AccountName: winlog.event_data.AccountName
  AllowedToDelegateTo: winlog.event_data.AllowedToDelegateTo
  AttributeLDAPDisplayName: winlog.event_data.AttributeLDAPDisplayName
  AuditPolicyChanges: winlog.event_data.AuditPolicyChanges
  AuthenticationPackageName: winlog.event_data.AuthenticationPackageName
  CallingProcessName: winlog.event_data.CallingProcessName
  Channel: winlog.channel
  ComputerName: winlog.computer_name
  EventType: winlog.event_data.EventType
  FailureReason: winlog.event_data.FailureCode
  FileName: winlog.event_data.FileName
  GrantedAccess: winlog.event_data.GrantedAccess
  Hashes: winlog.event_data.Hashes
  HiveName: winlog.event_data.HiveName
  IpAddress: winlog.event_data.IpAddress
  IpPort: winlog.event_data.IpPort
  KeyLength: winlog.event_data.KeyLength
  LogonProcessName: winlog.event_data.LogonProcessName
  LogonType: winlog.event_data.LogonType
  LinkName: winlog.event_data.LinkName
  MemberName: winlog.event_data.MemberName
  MemberSid: winlog.event_data.MemberSid
  NewProcessName: winlog.event_data.NewProcessName
  ObjectClass: winlog.event_data.ObjectClass
  ObjectName: winlog.event_data.ObjectName
  ObjectType: winlog.event_data.ObjectType
  ObjectValueName: winlog.event_data.ObjectValueName
  Path: winlog.event_data.Path
  CommandLine: winlog.event_data.ProcessCommandLine
  OldUacValue: winlog.event_data.OldUacValue
  CertIssuerName: winlog.event_data.CertIssuerName
  SubStatus: winlog.event_data.SubStatus
  DisplayName: winlog.event_data.DisplayName
  TaskContent: winlog.event_data.TaskContent
  ServiceSid: winlog.event_data.ServiceSid
  CertThumbprint: winlog.event_data.CertThumbprint
  ClassName: winlog.event_data.ClassName
  NotificationPackageName: winlog.event_data.NotificationPackageName
  NewSd: winlog.event_data.NewSd
  TestSigning: winlog.event_data.TestSigning
  TargetInfo: winlog.event_data.TargetInfo
  ClientProcessId: winlog.event_data.ClientProcessId
  ParentProcessId: winlog.event_data.ParentProcessId
  AccessList: winlog.event_data.AccessList
  GroupMembership: winlog.event_data.GroupMembership
  FilterName: winlog.event_data.FilterName
  ChangeType: winlog.event_data.ChangeType
  LayerName: winlog.event_data.LayerName
  ServiceAccount: winlog.event_data.ServiceAccount
  AttributeValue: winlog.event_data.AttributeValue
  SessionName: winlog.event_data.SessionName
  TaskName: winlog.event_data.TaskName
  ObjectDN: winlog.event_data.ObjectDN
  TemplateContent: winlog.event_data.TemplateContent
  NewTemplateContent: winlog.event_data.NewTemplateContent
  SourcePort: winlog.event_data.SourcePort
  PasswordLastSet: winlog.event_data.PasswordLastSet
  PrivilegeList: winlog.event_data.PrivilegeList
  DeviceDescription: winlog.event_data.DeviceDescription
  TargetServerName: winlog.event_data.TargetServerName
  NewTargetUserName: winlog.event_data.NewTargetUserName
  OperationType: winlog.event_data.OperationType
  DestPort: winlog.event_data.DestPort
  ServiceStartType: winlog.event_data.ServiceStartType
  OldTargetUserName: winlog.event_data.OldTargetUserName
  UserPrincipalName: winlog.event_data.UserPrincipalName
  Accesses: winlog.event_data.Accesses
  DnsHostName: winlog.event_data.DnsHostName
  DisableIntegrityChecks: winlog.event_data.DisableIntegrityChecks
  AuditSourceName: winlog.event_data.AuditSourceName
  Workstation: winlog.event_data.Workstation
  DestAddress: winlog.event_data.DestAddress
  PreAuthType: winlog.event_data.PreAuthType
  SecurityPackageName: winlog.event_data.SecurityPackageName
  SubjectLogonId: winlog.event_data.SubjectLogonId
  NewUacValue: winlog.event_data.NewUacValue
  EnabledPrivilegeList: winlog.event_data.EnabledPrivilegeList
  RelativeTargetName: winlog.event_data.RelativeTargetName
  CertSerialNumber: winlog.event_data.CertSerialNumber
  SidHistory: winlog.event_data.SidHistory
  TargetLogonId: winlog.event_data.TargetLogonId
  KernelDebug: winlog.event_data.KernelDebug
  CallerProcessName: winlog.event_data.CallerProcessName
  ProcessName: winlog.event_data.ProcessName
  Properties: winlog.event_data.Properties
  UserAccountControl: winlog.event_data.UserAccountControl
  RegistryValue: winlog.event_data.RegistryValue
  SecurityID: winlog.event_data.SecurityID
  ServiceFileName: winlog.event_data.ServiceFileName
  SecurityDescriptor: winlog.event_data.SecurityDescriptor
  ServiceName: winlog.event_data.ServiceName
  ShareName: winlog.event_data.ShareName
  NewValue: winlog.event_data.NewValue
  Source: winlog.event_data.Source
  Status: winlog.event_data.Status
  SubjectDomainName: winlog.event_data.SubjectDomainName
  SubjectUserName: winlog.event_data.SubjectUserName
  SubjectUserSid: winlog.event_data.SubjectUserSid
  SourceAddr: winlog.event_data.SourceAddr
  SourceAddress: winlog.event_data.SourceAddress
  TargetName: winlog.event_data.TargetName
  ServicePrincipalNames: winlog.event_data.ServicePrincipalNames
  TargetDomainName: winlog.event_data.TargetDomainName
  TargetSid: winlog.event_data.TargetSid
  TargetUserName: winlog.event_data.TargetUserName
  ObjectServer: winlog.event_data.ObjectServer
  TargetUserSid: winlog.event_data.TargetUserSid
  TicketEncryptionType: winlog.event_data.TicketEncryptionType
  TicketOptions: winlog.event_data.TicketOptions
  WorkstationName: winlog.event_data.WorkstationName
  TransmittedServices: winlog.event_data.TransmittedServices
  AuthenticationAlgorithm: winlog.event_data.AuthenticationAlgorithm
  LayerRTID: winlog.event_data.LayerRTID
  BSSID: winlog.event_data.BSSID
  BSSType: winlog.event_data.BSSType
  CipherAlgorithm: winlog.event_data.CipherAlgorithm
  ConnectionId: winlog.event_data.ConnectionId
  ConnectionMode: winlog.event_data.ConnectionMode
  InterfaceDescription: winlog.event_data.InterfaceDescription
  InterfaceGuid: winlog.event_data.InterfaceGuid
  OnexEnabled: winlog.event_data.OnexEnabled
  PHYType: winlog.event_data.PHYType
  ProfileName: winlog.event_data.ProfileName
  SSID: winlog.event_data.SSID
  Domain: winlog.event_data.Domain
  ServiceType: winlog.event_data.ServiceType
  SourceName: winlog.event_data.SourceName
  StartType: winlog.event_data.StartType
  UserID: winlog.event_data.UserID
  ParentProcessName: winlog.event_data.ParentProcessName
  Service: winlog.event_data.Service
