platform: LogScale
source: windows_application



field_mapping:
  Provider_Name: winlog.provider_name
  EventID: winlog.event_id
  Data: winlog.event_data.Data
  Message: winlog.event_data.Message
  Level: winlog.opcode